services:

  postgres:
    image: postgres:16
    container_name: ecommerce-postgres

    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce
      POSTGRES_DB: ecommerce

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    container_name: ecommerce-airflow

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    environment:
      ENVIRONMENT: dev

      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./dbt:/opt/airflow/dbt
      - ./config:/opt/airflow/config

    command: standalone


volumes:
  postgres_data: